apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: qa6bhrwdh-nodejs-gitops
  description: This is GitOps manifest for qa6bhrwdh-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=qa6bhrwdh-nodejs
    backstage.io/kubernetes-id: qa6bhrwdh-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: qa6bhrwdh-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:qa6bhrwdh-nodejs
