apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qa6bhrwdh-nodejs
  janus-idp.io/tekton: qa6bhrwdh-nodejs
  backstage.io/kubernetes-id: qa6bhrwdh-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: qa6bhrwdh-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
