apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: qa6bhrwdh-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qa6bhrwdh-nodejs 
  name: qa6bhrwdh-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: qa6bhrwdh-nodejs 
